{
 "title": "Rocket Pool Dashboard Finances",
 "description": "This is the standard dashboard for Rocket Pool node operators that use Nimbus.",
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 1, "w": 9, "x": 13, "y": 0 }, "options": { "content": "<br/>s" } },
  {
   "title": "ETH Price (ETH / USD)",
   "type": "stat",
   "description": "The amount of USD that 1 ETH is worth.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cryptocurrency_price{job=~\"json_exporter\",symbol=~\"ETH\"}"
    }
   ]
  },
  {
   "title": "RPL Price (RPL / USD)",
   "type": "stat",
   "description": "The amount of RPL that 1 USD is worth, as reported by the CoinAPI.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cryptocurrency_price{job=\"json_exporter\",symbol=\"RPL\"}"
    }
   ]
  },
  {
   "title": "Total Rewards Value",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(rocketpool_node_claimed_eth_rewards{job=\"rocketpool\"} + rocketpool_node_unclaimed_eth_rewards{job=\"rocketpool\"}) * on() cryptocurrency_price{symbol=~\"ETH\"}",
     "legendFormat": "Smoothing ETH rewards"
    },
    {
     "expr": "(rocketpool_node_beacon_share{job=\"rocketpool\"} - rocketpool_node_deposited_eth{job=\"rocketpool\"}) * on() cryptocurrency_price{symbol=~\"ETH\"}",
     "legendFormat": "Beacon ETH rewards"
    },
    {
     "expr": "  (rocketpool_node_unclaimed_rewards{job=\"rocketpool\"} +\n    rocketpool_node_cumulative_rpl_rewards{job=\"rocketpool\"})\n  * on() cryptocurrency_price{job=\"json_exporter\",symbol=~\"RPL\"}\n\n\n",
     "legendFormat": "RPL rewards"
    }
   ]
  },
  {
   "title": "Total Staked Value",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "rocketpool_node_effective_staked_rpl{job=\"rocketpool\"} * on() cryptocurrency_price{symbol=~\"RPL\"}\n\n\n",
     "legendFormat": "RPL Staked"
    },
    {
     "expr": "rocketpool_node_deposited_eth{job=\"rocketpool\"} * on() cryptocurrency_price{symbol=~\"ETH\"}",
     "legendFormat": "ETH Staked"
    }
   ]
  },
  {
   "title": "Total Value",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (rocketpool_node_effective_staked_rpl{job=\"rocketpool\"} + rocketpool_node_unclaimed_rewards{job=\"rocketpool\"} +\n    rocketpool_node_cumulative_rpl_rewards{job=\"rocketpool\"})\n  * on() cryptocurrency_price{job=\"json_exporter\",symbol=\"RPL\"}\n)\n+\n(\n  rocketpool_node_beacon_share{job=\"rocketpool\"} * on() cryptocurrency_price{symbol=~\"ETH\"}\n)\n+\n(\n  (rocketpool_node_claimed_eth_rewards{job=\"rocketpool\"} + rocketpool_node_unclaimed_eth_rewards{job=\"rocketpool\"}) * on() cryptocurrency_price{symbol=~\"ETH\"}\n)"
    }
   ]
  },
  {
   "title": "Your APR (7D)",
   "type": "stat",
   "description": "Your APR from Beacon Chain rewards, which includes the your minipool's commission.\n\nCalculated by comparing today's balance with the balance from 7 days ago, so this is your average APR over the last week.",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((rocketpool_node_beacon_share{job=\"rocketpool\"}) - (rocketpool_node_beacon_share{job=\"rocketpool\"} offset 7d != 0)) / rocketpool_node_deposited_eth{job=\"rocketpool\"} * (365/7)"
    }
   ]
  },
  {
   "title": "Your APR (30D)",
   "type": "stat",
   "description": "Your APR from Beacon Chain rewards, which includes the your minipool's commission.\n\nCalculated by comparing today's balance with the balance from 7 days ago, so this is your average APR over the last week.",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((rocketpool_node_beacon_share{job=\"rocketpool\"}) - (rocketpool_node_beacon_share{job=\"rocketpool\"} offset 30d != 0)) / rocketpool_node_deposited_eth{job=\"rocketpool\"} * (365/30)"
    }
   ]
  }
 ]
}